/**
 * Verified Top-Ranked Market Baseline for Lima, Peru
 * Combines Google Organic Search, Google Maps Local 3-Pack, and Industry Audits (2026)
 */

export const TOP_RANKED_LIMA_AGENCIES = [
  {
    name: 'Staff Digital',
    domain: 'staffdigital.pe',
    url: 'https://staffdigital.pe',
    primaryDistrict: 'Miraflores / San Isidro',
    districtsCovered: ['Miraflores', 'San Isidro', 'Santiago de Surco', 'San Borja', 'Lima Metropolitana'],
    tier: 1,
    googleMapsRank: 'Top 1-3 en Lima Centro y Corporativo',
    googleSearchPosition: 'Top 1-3 orgánico ("agencia diseño web lima")',
    approxRating: 4.8,
    reviewsCount: 140,
    positioning: 'Agencia Digital B2B / Corporativa & UX/UI Premium',
    targetAudience: 'Empresas medianas y grandes, corporativos B2B',
    estimatedPriceRange: 'S/ 3,500 - S/ 15,000+',
    coreServices: ['Diseño Web UX/UI', 'E-commerce', 'Branding', 'Marketing Digital 360'],
    flagshipCopy: 'Diseñamos experiencias digitales que transforman marcas y multiplican resultados comerciales.',
    strengths: 'Gran autoridad de dominio (.pe), portafolio corporativo impecable, alta presencia SEO multianual.'
  },
  {
    name: 'Staff Creativa',
    domain: 'staffcreativa.pe',
    url: 'https://staffcreativa.pe',
    primaryDistrict: 'Miraflores',
    districtsCovered: ['Miraflores', 'San Isidro', 'Lima Metropolitana'],
    tier: 1,
    googleMapsRank: 'Top 3 en Miraflores / Lima',
    googleSearchPosition: 'Top 1-5 orgánico histórico',
    approxRating: 4.7,
    reviewsCount: 125,
    positioning: 'Branding estratégico, diseño web y tiendas virtuales',
    targetAudience: 'Empresas consolidadas que buscan diferenciación visual y marca sólida',
    estimatedPriceRange: 'S/ 3,000 - S/ 12,000',
    coreServices: ['Diseño Web', 'Branding y Logotipos', 'Tiendas Virtuales', 'Marketing Digital'],
    flagshipCopy: 'Más de 15 años creando sitios web y marcas memorables que conectan con la mente y el corazón de tu audiencia.',
    strengths: 'Especialistas en branding + web; autoridad de marca muy alta en Perú.'
  },
  {
    name: 'Flama Creators',
    domain: 'flamacreators.com',
    url: 'https://flamacreators.com',
    primaryDistrict: 'Miraflores / San Isidro',
    districtsCovered: ['Miraflores', 'San Isidro', 'Santiago de Surco', 'La Molina', 'Lima Metropolitana'],
    tier: 1,
    googleMapsRank: 'Top 5 en Google Maps',
    googleSearchPosition: 'Top 1-3 orgánico en tendencias 2025-2026 ("mejor agencia diseño web lima")',
    approxRating: 4.9,
    reviewsCount: 88,
    positioning: 'Diseño Web Mobile-First, Performance y Optimización para IA & SEO',
    targetAudience: 'Empresas modernas, startups y marcas orientadas a conversión veloz',
    estimatedPriceRange: 'S/ 2,500 - S/ 9,000',
    coreServices: ['Diseño Mobile-First', 'SEO Avanzado y GEO/AI Search', 'Desarrollo Web', 'Optimización de Conversión'],
    flagshipCopy: 'Páginas web ultrarrápidas, mobile-first y optimizadas para que Google y la IA recomienden tu negocio.',
    strengths: 'Discurso muy moderno, foco en velocidad extrema y visibilidad en motores de búsqueda modernos.'
  },
  {
    name: 'KOM (Agencia KOM)',
    domain: 'kom.pe',
    url: 'https://kom.pe',
    primaryDistrict: 'San Isidro / Miraflores',
    districtsCovered: ['San Isidro', 'Miraflores', 'San Borja', 'Lima Metropolitana'],
    tier: 1,
    googleMapsRank: 'Top 5 en San Isidro',
    googleSearchPosition: 'Top 1-3 orgánico en comparativas de precios y diseño web WordPress',
    approxRating: 4.8,
    reviewsCount: 95,
    positioning: 'Diseño WordPress profesional, SEO técnico y transparencia total de precios',
    targetAudience: 'Pymes y profesionales que exigen claridad de costos y rapidez',
    estimatedPriceRange: 'S/ 1,250 - S/ 3,800 (Precios públicos)',
    coreServices: ['Diseño Web WordPress', 'Posicionamiento SEO', 'Google Ads', 'Mantenimiento Web'],
    flagshipCopy: 'Páginas web profesionales listas para captar clientes desde el primer día, sin costos ocultos.',
    strengths: 'Pioneros en publicar tarifas transparentes, gran conversión por honestidad y claridad de oferta.'
  },
  {
    name: 'Hosting.com.pe',
    domain: 'hosting.com.pe',
    url: 'https://hosting.com.pe',
    primaryDistrict: 'Lima Cercado / San Borja',
    districtsCovered: ['Lima Cercado', 'San Borja', 'Santiago de Surco', 'Todo Lima y Provincias'],
    tier: 1,
    googleMapsRank: 'Top 3 en infraestructura y web',
    googleSearchPosition: 'Top 1 en "creacion de paginas web lima" y "diseño web hosting peru"',
    approxRating: 4.6,
    reviewsCount: 310,
    positioning: 'Paquete Todo-en-Uno: Dominio + Hosting de alta velocidad + Diseño Web',
    targetAudience: 'Emprendedores, pequeñas y medianas empresas que buscan solución completa sin enredos técnicos',
    estimatedPriceRange: 'S/ 800 - S/ 2,800',
    coreServices: ['Diseño Web Llave en Mano', 'Hosting Cloud Perú', 'Dominio .pe / .com', 'Correos Corporativos'],
    flagshipCopy: 'Tu negocio en internet en tiempo récord: web profesional + hosting de alta velocidad incluido.',
    strengths: 'Más de 18 años en el mercado; infraestructura propia de servidores en Perú; captación masiva.'
  },
  {
    name: 'Linklab',
    domain: 'linklab.pe',
    url: 'https://linklab.pe',
    primaryDistrict: 'San Isidro',
    districtsCovered: ['San Isidro', 'Miraflores', 'La Molina'],
    tier: 1,
    googleMapsRank: 'Top 5 corporativo',
    googleSearchPosition: 'Top 5 en desarrollos UX/UI a medida y software',
    approxRating: 4.9,
    reviewsCount: 65,
    positioning: 'Laboratorio de UX/UI, desarrollo web a medida e integraciones complejas',
    targetAudience: 'Empresas medianas/grandes que necesitan automatización de procesos y plataformas web personalizadas',
    estimatedPriceRange: 'S/ 5,000 - S/ 25,000',
    coreServices: ['Investigación UX/UI', 'Desarrollo Web Custom', 'Integración de APIs y Sistemas', 'Software a Medida'],
    flagshipCopy: 'Transformamos problemas operativos complejos en interfaces intuitivas y sistemas digitales de alto rendimiento.',
    strengths: 'Enfoque de ingeniería y arquitectura de software; no usan plantillas baratas; tickets altos.'
  },
  {
    name: 'Webtilia',
    domain: 'webtilia.com',
    url: 'https://webtilia.com',
    primaryDistrict: 'San Isidro',
    districtsCovered: ['San Isidro', 'Miraflores', 'Surco'],
    tier: 1,
    googleMapsRank: 'Top 5 San Isidro financiero',
    googleSearchPosition: 'Top 5 en agencias digitales integrales',
    approxRating: 4.7,
    reviewsCount: 110,
    positioning: 'Agencia de Marketing Digital 360, Campañas y Ecosistemas Web',
    targetAudience: 'Marcas de consumo masivo, retail, inmobiliarias y corporaciones',
    estimatedPriceRange: 'S/ 4,000 - S/ 20,000',
    coreServices: ['Desarrollo Web y Landing Pages', 'Marketing Digital', 'Social Media', 'Medios y Performance'],
    flagshipCopy: 'Estrategias digitales que construyen marcas y detonan conversiones a escala.',
    strengths: 'Fuerza creativa y reputación en el círculo de agencias publicitarias de San Isidro.'
  },
  {
    name: 'LM Marketing',
    domain: 'lmmarketing.com.pe',
    url: 'https://lmmarketing.com.pe',
    primaryDistrict: 'Miraflores',
    districtsCovered: ['Miraflores', 'San Isidro', 'Surco', 'San Borja'],
    tier: 1,
    googleMapsRank: 'Top 5 Miraflores',
    googleSearchPosition: 'Top 5 orgánico e-commerce y diseño corporativo',
    approxRating: 4.8,
    reviewsCount: 75,
    positioning: 'Especialistas en Tiendas Virtuales, Catálogos y Web Corporativa de Alta Conversión',
    targetAudience: 'Empresas comerciales, importadoras, distribuidores y retailers',
    estimatedPriceRange: 'S/ 2,000 - S/ 7,500',
    coreServices: ['Diseño Web', 'E-commerce con Pasarelas de Pago', 'SEO y Posicionamiento', 'Campañas de Tráfico'],
    flagshipCopy: 'Convierte visitantes en clientes recurrentes con tiendas online optimizadas y páginas web de alto impacto.',
    strengths: 'Fuerte dominio en e-commerce local y pasarelas de pago peruanas (Culqi, Niubiz, Mercado Pago, Izipay).'
  },
  {
    name: 'Crealo Studio',
    domain: 'crealostudio.com',
    url: 'https://crealostudio.com',
    primaryDistrict: 'Santiago de Surco',
    districtsCovered: ['Santiago de Surco', 'La Molina', 'San Borja', 'Miraflores'],
    tier: 1,
    googleMapsRank: 'Top 1-3 en Surco (Av. La Encalada)',
    googleSearchPosition: 'Top 5 en búsquedas de Surco y Lima Este',
    approxRating: 4.8,
    reviewsCount: 82,
    positioning: 'Estudio de diseño web boutique y branding corporativo',
    targetAudience: 'Negocios de Surco/La Molina, clínicas, firmas legales y consultoras',
    estimatedPriceRange: 'S/ 2,200 - S/ 8,000',
    coreServices: ['Diseño Web Personalizado', 'Branding Corporativo', 'Catálogos Digitales', 'SEO Local'],
    flagshipCopy: 'Diseño web que proyecta el prestigio y la calidad real de tu empresa.',
    strengths: 'Excelente presencia local en la zona empresarial de El Polo / Chacarilla / La Encalada.'
  },
  {
    name: 'Cybernova',
    domain: 'cybernova.pe',
    url: 'https://cybernova.pe',
    primaryDistrict: 'Los Olivos (Lima Norte)',
    districtsCovered: ['Los Olivos', 'San Martín de Porres', 'Independencia', 'Comas', 'Lima Norte'],
    tier: 2,
    googleMapsRank: 'Top 1 en Los Olivos y Lima Norte (Av. Antúnez de Mayolo)',
    googleSearchPosition: 'Top 1 en búsquedas de diseño web Lima Norte',
    approxRating: 4.9,
    reviewsCount: 160,
    positioning: 'El referente consolidado de diseño web, aulas virtuales y marketing en Lima Norte (18+ años)',
    targetAudience: 'Pymes comerciales, institutos, colegios, distribuidores e importadores de Lima Norte',
    estimatedPriceRange: 'S/ 950 - S/ 3,500',
    coreServices: ['Diseño de Páginas Web', 'Tiendas Virtuales', 'Aulas Virtuales Moodle', 'SEO y Google Ads'],
    flagshipCopy: 'Potencia tus ventas con una página web moderna, rápida y ubicada en los primeros lugares de Google.',
    strengths: 'Líder indiscutible en Lima Norte con 18+ años de fidelidad y ubicación física en pleno corazón comercial.'
  },
  {
    name: 'TalentuPerú',
    domain: 'talentuperu.com',
    url: 'https://talentuperu.com',
    primaryDistrict: 'Los Olivos (Lima Norte)',
    districtsCovered: ['Los Olivos', 'SMP', 'Comas', 'Lima Metropolitana'],
    tier: 2,
    googleMapsRank: 'Top 2 en Los Olivos',
    googleSearchPosition: 'Top 3 en diseño web enfocado a captar prospectos comerciales',
    approxRating: 4.8,
    reviewsCount: 92,
    positioning: 'Desarrollo web enfocado 100% en captar llamadas y mensajes de WhatsApp para pymes',
    targetAudience: 'Empresas de servicios, talleres, logística y comercio local',
    estimatedPriceRange: 'S/ 850 - S/ 2,800',
    coreServices: ['Páginas Web para Contactos', 'Tiendas Online', 'Posicionamiento en Google Maps', 'Email Corporativo'],
    flagshipCopy: 'No queremos que solo tengas una web; queremos que tu teléfono y WhatsApp no dejen de sonar con clientes.',
    strengths: 'Discurso muy pragmático orientado a resultados directos (leads por WhatsApp), excelente empatía con dueños de pymes.'
  },
  {
    name: 'Agencia Web Perú',
    domain: 'agenciawebperu.com',
    url: 'https://agenciawebperu.com',
    primaryDistrict: 'Miraflores',
    districtsCovered: ['Miraflores', 'Lince', 'Jesús María', 'Lima Cercado'],
    tier: 1,
    googleMapsRank: 'Top 5 Miraflores',
    googleSearchPosition: 'Top 5 orgánico "agencia web peru"',
    approxRating: 4.7,
    reviewsCount: 70,
    positioning: 'Soluciones web ágiles y posicionamiento orgánico en motores de búsqueda',
    targetAudience: 'Emprendedores y profesionales independientes',
    estimatedPriceRange: 'S/ 1,100 - S/ 3,500',
    coreServices: ['Páginas Web Autoadministrables', 'SEO Local', 'Landing Pages', 'Rediseño Web'],
    flagshipCopy: 'Páginas web administrables, rápidas y pensadas para escalar.',
    strengths: 'Nombre de dominio de alta intención SEO y posicionamiento constante.'
  },
  {
    name: 'Glob Digital',
    domain: 'globdigital.pe',
    url: 'https://globdigital.pe',
    primaryDistrict: 'Miraflores / Surco',
    districtsCovered: ['Miraflores', 'San Isidro', 'Surco'],
    tier: 1,
    googleMapsRank: 'Top 5 en reseñas de agencias',
    googleSearchPosition: 'Top 10 en diseño web y branding moderno',
    approxRating: 4.9,
    reviewsCount: 80,
    positioning: 'Agencia de experiencias digitales, diseño UX y performance marketing',
    targetAudience: 'Marcas con visión internacional y empresas medianas',
    estimatedPriceRange: 'S/ 2,800 - S/ 10,000',
    coreServices: ['Diseño y Desarrollo Web', 'E-commerce Avanzado', 'Performance Marketing', 'Diseño de Marca'],
    flagshipCopy: 'Creamos soluciones digitales que generan impacto real en el crecimiento de tu negocio.',
    strengths: 'Estética visual moderna y limpia; calificaciones altas en Clutch y Google.'
  },
  {
    name: 'Publinet',
    domain: 'publinet.com.pe',
    url: 'https://publinet.com.pe',
    primaryDistrict: 'San Isidro / San Borja',
    districtsCovered: ['San Isidro', 'San Borja', 'Lima Cercado'],
    tier: 1,
    googleMapsRank: 'Top 10 en agencias corporativas',
    googleSearchPosition: 'Top 5 en desarrollo web a medida corporativo',
    approxRating: 4.6,
    reviewsCount: 60,
    positioning: 'Desarrollo web corporativo robusto y aplicaciones empresariales a medida',
    targetAudience: 'Corporaciones, industrias y sector educativo/financiero',
    estimatedPriceRange: 'S/ 4,000 - S/ 18,000',
    coreServices: ['Desarrollo a Medida', 'Portales Web Corporativos', 'Intranets', 'Mantenimiento de Software'],
    flagshipCopy: 'Soluciones digitales seguras y escalables para grandes organizaciones.',
    strengths: 'Capacidad técnica en arquitecturas de backend robustas.'
  },
  {
    name: 'LevelUp Perú',
    domain: 'levelupperu.com',
    url: 'https://levelupperu.com',
    primaryDistrict: 'Surco / San Borja',
    districtsCovered: ['Santiago de Surco', 'San Borja', 'Miraflores'],
    tier: 1,
    googleMapsRank: 'Top 10 agencias modernas',
    googleSearchPosition: 'Top 5 en innovación y paneles de cliente',
    approxRating: 4.9,
    reviewsCount: 55,
    positioning: 'Webs ultra optimizadas con panel propio y enfoque en retorno de inversión',
    targetAudience: 'Negocios B2B y empresas de servicios profesionales',
    estimatedPriceRange: 'S/ 2,400 - S/ 7,000',
    coreServices: ['Diseño Web de Alta Conversión', 'SEO', 'Paneles de Gestión', 'Automatización de Ventas'],
    flagshipCopy: 'Lleva tu empresa al siguiente nivel con una plataforma digital que genera prospectos calificados.',
    strengths: 'Excelente servicio al cliente y métricas transparentes.'
  }
];
