import { useEffect, useState } from 'react';
import { AnimatePresence } from 'framer-motion';
import { AdminLogin } from '../../components/Admin/AdminLogin.jsx';
import { LeadDrawer } from '../../components/Admin/LeadDrawer.jsx';
import { isAdminAuthenticated, listLeads, subscribeToLeads, signOutAdmin } from '../../services/pocketbase.js';

export function Admin() {
  const [authenticated, setAuthenticated] = useState(isAdminAuthenticated());
  const [leads, setLeads] = useState([]);
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { if (!authenticated) return undefined; let active = true; listLeads().then(items => { if (active) setLeads(items); }).catch(() => setError('No se pudieron cargar los leads.')).finally(() => active && setLoading(false)); const unsubscribe = subscribeToLeads(event => { setLeads(current => { const index = current.findIndex(lead => lead.id === event.record.id); if (event.action === 'delete') return current.filter(lead => lead.id !== event.record.id); if (index === -1) return [event.record, ...current]; const next = [...current]; next[index] = event.record; return next; }); setSelected(current => current?.id === event.record.id ? event.record : current); }); return () => { active = false; unsubscribe(); }; }, [authenticated]);
  if (!authenticated) return <AdminLogin onAuthenticated={() => setAuthenticated(true)} />;
  return <main className="admin-shell"><header className="admin-topbar"><div><span className="eyebrow">Centro de mando</span><h1>Pipeline de leads</h1></div><div className="admin-actions"><span className="live-status"><i /> En tiempo real</span><button className="button ghost" onClick={() => { signOutAdmin(); setAuthenticated(false); }}>Cerrar sesión</button></div></header><section className="admin-summary"><div><span>Leads totales</span><strong>{leads.length}</strong></div><div><span>Nuevos</span><strong>{leads.filter(lead => (lead.status || 'Nuevo') === 'Nuevo').length}</strong></div><div><span>En auditoría</span><strong>{leads.filter(lead => lead.status === 'En Auditoría').length}</strong></div></section><section className="lead-table-wrap"><div className="table-heading"><h2>Actividad reciente</h2><span>{leads.length} registros</span></div>{error && <p className="error">{error}</p>}{loading ? <p className="empty-state">Cargando leads...</p> : leads.length === 0 ? <p className="empty-state">Aún no hay leads capturados.</p> : <div className="table-scroll"><table><thead><tr><th>Lead</th><th>Empresa</th><th>Nicho</th><th>Estado</th><th>Recibido</th></tr></thead><tbody>{leads.map(lead => <tr key={lead.id} onClick={() => setSelected(lead)} tabIndex="0" onKeyDown={event => event.key === 'Enter' && setSelected(lead)}><td><strong>{lead.name || 'Sin nombre'}</strong><small>{lead.email}</small></td><td>{lead.company || '—'}</td><td>{lead.niche || '—'}</td><td><span className="status-badge">{lead.status || 'Nuevo'}</span></td><td>{new Date(lead.created).toLocaleDateString('es-MX')}</td></tr>)}</tbody></table></div>}</section><AnimatePresence>{selected && <LeadDrawer lead={selected} onClose={() => setSelected(null)} onUpdated={updated => { setSelected(updated); setLeads(current => current.map(lead => lead.id === updated.id ? updated : lead)); }} />}</AnimatePresence></main>;
}
